import 'package:antwise/domain/entities/table_column_type.dart';
import 'package:antwise/presentation/widgets/searchable_dropdown_field.dart';
import 'package:flutter/material.dart';

String columnDataTypeLabel(TableColumnType type) => switch (type) {
  TableColumnType.text => 'Text',
  TableColumnType.number => 'Number',
  TableColumnType.date => 'Date',
  TableColumnType.boolean => 'Boolean',
  TableColumnType.dropdown => 'Dropdown',
  TableColumnType.formula => 'Formula',
  TableColumnType.autoGenerated => 'Auto Generated',
  TableColumnType.image => 'Image',
  TableColumnType.file => 'File',
};

/// Searchable replacement for [DropdownButtonFormField] of [TableColumnType].
class SearchableColumnTypeField extends StatelessWidget {
  const SearchableColumnTypeField({
    super.key,
    required this.selectedType,
    required this.onChanged,
    required this.allowedTypes,
    this.label = 'Data type',
  });

  final TableColumnType? selectedType;
  final ValueChanged<TableColumnType> onChanged;
  final List<TableColumnType> allowedTypes;
  final String label;

  @override
  Widget build(BuildContext context) {
    return SearchableDropdownField<TableColumnType>(
      options: allowedTypes,
      value: selectedType,
      optionLabel: columnDataTypeLabel,
      label: label,
      hintText: 'Search data type…',
      onChanged: onChanged,
    );
  }
}
