import 'package:antwise/domain/dropdown/dropdown_column_options.dart';
import 'package:antwise/domain/entities/table_column_entity.dart';
import 'package:antwise/domain/entities/table_column_type.dart';
import 'package:antwise/domain/entities/table_row_entity.dart';
import 'package:antwise/domain/validation/table_text_value_validator.dart';
import 'package:flutter/services.dart';

/// Restricts input to digits and at most one decimal point (non-negative).
final class DecimalNumericInputFormatter extends TextInputFormatter {
  const DecimalNumericInputFormatter();

  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    final String t = newValue.text;
    if (t.isEmpty) {
      return newValue;
    }
    if (RegExp(r'^\d*\.?\d*$').hasMatch(t)) {
      return newValue;
    }
    return oldValue;
  }
}

/// Schema-driven validation for the add/edit table row modal.
abstract final class TableRowModalFieldValidators {
  static String? validate({
    required TableColumnEntity col,
    String? textValue,
    bool? boolValue,
    DateTime? dateValue,
    String? imageValue,
    String? fileValue,
    Map<String, List<TableRowEntity>>? rowsByTableForDropdown,
  }) {
    switch (col.type) {
      case TableColumnType.boolean:
        if (col.isRequired && boolValue != true) {
          return 'This field is required.';
        }
        return null;
      case TableColumnType.date:
        if (col.isRequired && dateValue == null) {
          return 'This field is required.';
        }
        return null;
      case TableColumnType.image:
        if (col.isRequired &&
            (imageValue == null || imageValue.trim().isEmpty)) {
          return 'Please select a file.';
        }
        return null;
      case TableColumnType.file:
        if (col.isRequired &&
            (fileValue == null || fileValue.trim().isEmpty)) {
          return 'Please select a file.';
        }
        return null;
      case TableColumnType.number:
        return _validateNumber(textValue, col);
      case TableColumnType.formula:
        return _validateFormula(textValue, col.isRequired);
      case TableColumnType.dropdown:
        final String t = textValue?.trim() ?? '';
        if (col.isRequired && t.isEmpty) {
          return 'This field is required.';
        }
        final List<String> allowed =
            rowsByTableForDropdown == null
                ? col.dropdownOptions
                : DropdownColumnOptions.resolve(
                    column: col,
                    rowsByTableId: rowsByTableForDropdown,
                  );
        if (t.isNotEmpty &&
            allowed.isNotEmpty &&
            !allowed.contains(t)) {
          return 'Please choose a valid option.';
        }
        return null;
      case TableColumnType.text:
        return TableTextValueValidator.validate(
          col: col,
          raw: textValue,
        );
      case TableColumnType.autoGenerated:
        final String t = textValue?.trim() ?? '';
        if (col.isRequired && t.isEmpty) {
          return 'This field is required.';
        }
        return null;
    }
  }

  /// Whole numbers or decimals with at least one digit after `.` (rejects `123.`).
  static final RegExp _strictPositiveDecimal = RegExp(r'^\d+(\.\d+)?$');

  static String? _validateNumber(String? raw, TableColumnEntity col) {
    final String t = raw?.trim() ?? '';
    if (col.isRequired && t.isEmpty) {
      return 'This field is required.';
    }
    if (t.isEmpty) {
      return null;
    }
    final bool allowDecimals = col.numberIntegerOnly ? false : col.numberAllowDecimals;
    final RegExp pattern = allowDecimals
        ? (col.numberPositiveOnly
            ? RegExp(r'^\d+(\.\d+)?$')
            : RegExp(r'^-?\d+(\.\d+)?$'))
        : (col.numberPositiveOnly ? RegExp(r'^\d+$') : RegExp(r'^-?\d+$'));
    if (!pattern.hasMatch(t)) {
      return 'Please enter a valid number.';
    }
    final double? parsed = double.tryParse(t);
    if (parsed == null) {
      return 'Please enter a valid number.';
    }
    if (col.numberPositiveOnly && parsed < 0) {
      return 'Only positive numbers are allowed.';
    }
    if (col.numberMinValue != null && parsed < col.numberMinValue!) {
      return 'Value must be at least ${col.numberMinValue}.';
    }
    if (col.numberMaxValue != null && parsed > col.numberMaxValue!) {
      return 'Value must be at most ${col.numberMaxValue}.';
    }
    return null;
  }

  static String? _validateFormula(String? raw, bool isRequired) {
    final String t = raw?.trim() ?? '';
    if (isRequired && t.isEmpty) {
      return 'This field is required.';
    }
    if (t.isEmpty) {
      return null;
    }
    if (!_strictPositiveDecimal.hasMatch(t)) {
      return 'Invalid formula value.';
    }
    if (double.tryParse(t) == null) {
      return 'Invalid formula value.';
    }
    return null;
  }
}
