/// Application schema, formula, and widget reference for Build-mode prompts.
///
/// The on-device ekv1280 model caps **input + output** at 1280 tokens, so only
/// [compactApplicationReference] is sent to the model. [applicationReference] is
/// kept for logs / debugging.
abstract final class AiBuildSchemaDocumentation {
  /// Short formula-only block for the plan-aware builder (keeps token budget).
  static String compactFormulaReference() {
    return '''
Formulas:[Col] or "T"."C" if spaces.Fns:TODAY(),DATE_ADD(date,days),DAYS_AGO(n),SUM,AVG,COUNT,IF,COUNTIF,LOOKUP.Ops:+-*/==!=<><= >=.
Date cards: today SUM(IF("T".Date=TODAY(),"T"."Total Amount",0)); last 7d SUM(IF("T".Date>=DAYS_AGO(7),IF("T".Date<=TODAY(),"T"."Total Amount",0),0)); last 30d use DAYS_AGO(30). Use DATE_ADD(TODAY(),-7) same as DAYS_AGO(7). No TODAY()-7 (invalid). Quote spaced names in JSON.
''';
  }

  /// Token-efficient reference (~350 tokens) injected into the monolithic system prompt.
  static String compactApplicationReference() {
    return '''
REF|${compactFormulaReference().trim()}
Rules:exact WORKSPACE names;no invented fns/cols;formula cols depend on base cols;card/chart formulas→update_widget not update_table;summary→kind:summary+summary{sourceTable,groupBy,aggregate,operation:sum|count|avg|min|max}(omit columns).
Table std:columns[{name,type}] types text|number|date|boolean|dropdown|formula|image|email|phone|currency|autoGenerated|file.AI create_table cols:text|number|date|boolean|dropdown only.
Summary:aggregates source table by groupBy;ops sum|count|avg|min|max.
Card:create_card_widget{pageRef,tableRef,title,columnName?,formula?} KPI/totals.
Chart:create_chart_widget{pageRef,tableRef,title,chartType:bar|line|pie,xColumn,yColumn}.
Deps:pages→tables+widgets;widgets→tableRef;summary→sourceTable.
''';
  }

  /// Full reference for log output only (not sent to the on-device model).
  static String applicationReference() => compactApplicationReference();
}
