import 'package:antwise/domain/entities/table_row_entity.dart';
import 'package:antwise/domain/entities/table_schema_entity.dart';
import 'package:antwise/domain/entities/table_column_type.dart';
import 'package:antwise/domain/formula/table_formula_evaluator.dart';

/// Resolves formula columns for AI context with per-request caching.
final class AiFormulaProcessor {
  AiFormulaProcessor();

  final Map<String, Map<String, dynamic>> _resolvedRowCache =
      <String, Map<String, dynamic>>{};

  void clearCache() => _resolvedRowCache.clear();

  Map<String, dynamic> resolveRowValues({
    required TableSchemaEntity schema,
    required TableRowEntity row,
    required List<TableSchemaEntity> allSchemas,
    required Map<String, List<TableRowEntity>> rowsByTableId,
  }) {
    final String cacheKey = '${row.tableId}:${row.id}';
    return _resolvedRowCache.putIfAbsent(
      cacheKey,
      () => TableFormulaEvaluator.resolveRowValues(
        schema: schema,
        row: row,
        allSchemas: allSchemas,
        rowsByTableId: rowsByTableId,
      ),
    );
  }

  /// Human-readable column names for formula / auto-generated fields on [schema].
  static Set<String> formulaColumnLabels(TableSchemaEntity schema) {
    final Set<String> labels = <String>{};
    for (final col in schema.columns) {
      if (col.type == TableColumnType.formula ||
          col.type == TableColumnType.autoGenerated) {
        final String name = col.name.trim();
        if (name.isNotEmpty) {
          labels.add(name);
        }
      }
    }
    return labels;
  }
}
