enum TableColumnType {
  text,
  number,
  date,
  boolean,
  dropdown,
  currency,
  formula,
  autoGenerated,
  image,
  file,
  ;

  static TableColumnType fromStorage(String value) {
    switch (value) {
      case 'number':
        return TableColumnType.number;
      case 'date':
        return TableColumnType.date;
      case 'boolean':
        return TableColumnType.boolean;
      case 'dropdown':
        return TableColumnType.dropdown;
      case 'currency':
        return TableColumnType.currency;
      case 'formula':
        return TableColumnType.formula;
      case 'autoGenerated':
        return TableColumnType.autoGenerated;
      case 'image':
        return TableColumnType.image;
      case 'file':
        return TableColumnType.file;
      default:
        return TableColumnType.text;
    }
  }

  String get storageValue => switch (this) {
    TableColumnType.text => 'text',
    TableColumnType.number => 'number',
    TableColumnType.date => 'date',
    TableColumnType.boolean => 'boolean',
    TableColumnType.dropdown => 'dropdown',
    TableColumnType.currency => 'currency',
    TableColumnType.formula => 'formula',
    TableColumnType.autoGenerated => 'autoGenerated',
    TableColumnType.image => 'image',
    TableColumnType.file => 'file',
  };
}
