enum TableColumnType {
  text,
  number,
  date,
  boolean,
  dropdown,
  formula,
  autoGenerated,
  image,
  file;

  static TableColumnType fromStorage(String value) {
    final String raw = value.trim();
    final String normalized =
        raw.startsWith('TableColumnType.')
            ? raw.substring('TableColumnType.'.length)
            : raw;
    switch (normalized.toLowerCase()) {
      case 'text':
        return TableColumnType.text;
      case 'number':
        return TableColumnType.number;
      case 'date':
        return TableColumnType.date;
      case 'boolean':
        return TableColumnType.boolean;
      case 'dropdown':
        return TableColumnType.dropdown;
      case 'formula':
        return TableColumnType.formula;
      case 'autogenerated':
        return TableColumnType.autoGenerated;
      case 'image':
        return TableColumnType.image;
      case 'file':
        return TableColumnType.file;
      default:
        return TableColumnType.text;
    }
  }

  String get storageValue => switch (this) {
    TableColumnType.text => 'text',
    TableColumnType.number => 'number',
    TableColumnType.date => 'date',
    TableColumnType.boolean => 'boolean',
    TableColumnType.dropdown => 'dropdown',
    TableColumnType.formula => 'formula',
    TableColumnType.autoGenerated => 'autoGenerated',
    TableColumnType.image => 'image',
    TableColumnType.file => 'file',
  };
}
