// Generates lib/core/icons/flutter_material_icons_map.g.dart from the Flutter SDK
// icons.dart. Run (from project root):
//   FLUTTER_ROOT=$HOME/development/flutter dart run tool/generate_flutter_material_icon_map.dart
// or:
//   dart run tool/generate_flutter_material_icon_map.dart /path/to/flutter

import 'dart:convert';
import 'dart:io';

final RegExp _iconLine = RegExp(
  r'^\s*static const IconData ([a-zA-Z0-9_]+) =',
  multiLine: false,
);

Future<void> main(List<String> args) async {
  final String? root =
      args.isNotEmpty
          ? args.first
          : Platform.environment['FLUTTER_ROOT'];
  if (root == null || root.isEmpty) {
    // ignore: avoid_print
    stderr.writeln(
      'Set FLUTTER_ROOT or pass the Flutter SDK path as the first argument.',
    );
    exitCode = 1;
    return;
  }
  final File iconsFile = File(
    '$root/packages/flutter/lib/src/material/icons.dart',
  );
  if (!iconsFile.existsSync()) {
    // ignore: avoid_print
    stderr.writeln('Not found: ${iconsFile.path}');
    exitCode = 1;
    return;
  }
  final String content = iconsFile.readAsStringSync();
  final Set<String> names = <String>{};
  for (final String line in const LineSplitter().convert(content)) {
    final RegExpMatch? m = _iconLine.firstMatch(line);
    if (m != null) {
      names.add(m.group(1)!);
    }
  }
  final List<String> sorted = names.toList()..sort();
  final StringBuffer b = StringBuffer();
  b.writeln('// GENERATED by tool/generate_flutter_material_icon_map.dart');
  b.writeln('// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars');
  b.writeln();
  b.writeln("import 'package:flutter/material.dart';");
  b.writeln();
  b.writeln('/// All `Icons.*` `IconData` symbols from the Flutter Material library.');
  b.writeln('/// Referencing this map links every icon: font subsetting may retain');
  b.writeln('/// a large Material font; see Flutter docs for `--tree-shake-icons`.');
  b.writeln('final Map<String, IconData> kFlutterMaterialIconsByName ='
      ' <String, IconData>{');
  for (final String n in sorted) {
    b.writeln("  '$n': Icons.$n,");
  }
  b.writeln('};');
  final File out = File('lib/core/icons/flutter_material_icons_map.g.dart');
  await out.parent.create(recursive: true);
  out.writeAsStringSync(b.toString());
  // ignore: avoid_print
  stdout.writeln('Wrote ${out.path} (${sorted.length} icons).');
}
